using UnityEngine;
using System.Collections;
using DG.Tweening;

public class RestartRotatingDisks : MonoBehaviour {
	public float rotationForce;
	public bool justdisk = false;
	// Use this for initialization
	void Start () {
//		GetComponent<Rigidbody2D> ().AddTorque (5f);

//		GetComponent<Rigidbody2D> ().Rotat
//		transform.Rot
//		restartDiskGroup.transform.DOMoveX (posX, 0.4f).SetEase(Ease.OutCubic);

		float tempo = UnityEngine.Random.Range (2f, 2.6f);
		float angle = UnityEngine.Random.Range  (-1, -360);
//		float force = UnityEngine.Random.Range (1,2);
		float force = rotationForce;
		angle = angle * (force);
		if(justdisk)
			transform.DORotate (new Vector3 (0, 0, angle), 4f, RotateMode.WorldAxisAdd);
		else
			transform.DORotate (new Vector3 ( angle,  angle, angle), 4f, RotateMode.FastBeyond360);
	}

	// Update is called once per frame
	void Update () {
	
	}
}
